# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-19 07:33
from __future__ import unicode_literals

import cars.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('mpg', models.CharField(max_length=30)),
                ('cylinders', models.CharField(max_length=30)),
                ('displacement', models.CharField(max_length=30)),
                ('horsepower', models.CharField(max_length=30)),
                ('weight', models.CharField(max_length=30)),
                ('acceleration', models.CharField(max_length=30)),
                ('year', models.PositiveIntegerField(validators=[cars.validators.validate_year])),
                ('price', models.CharField(max_length=30)),
                ('origin', models.CharField(help_text='Release country', max_length=40)),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Car',
                'verbose_name_plural': 'Cars',
            },
        ),
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=b'')),
                ('upload_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.Car')),
            ],
        ),
    ]
