# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-25 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='price',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
