# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-13 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_car_mongo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='mongo_id',
            field=models.CharField(default=None, max_length=16),
        ),
    ]
