# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-29 14:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0002_basketitem_cart_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basketitem',
            name='car',
        ),
        migrations.DeleteModel(
            name='BasketItem',
        ),
    ]
